version: "3.8"

services:

  ros2-base:
    build:
      context: "."
      target: ros2-base
    volumes:
      - "./ros2_ws/:/ros2_ws/"

  ros2-desktop:
    build:
      context: "."
      target: ros2-desktop
    ports:
      - "2222:22"
    volumes:
      - "./ros2_ws/:/ros2_ws/"

